### ISSUE TITLE
[BUG] Error reading jpg images

### ISSUE THREAD

**Issue by acorderob** [RupertAvery/DiffusionToolkit#106]
**Describe the bug**
Selecting jpg images fail with an error dialog and doesn't show them in preview. I removed one from the db and when refreshing it tries to add it but fails. See log below. This didn't happen with version 1.1.

**Version:**
1.2

**To Reproduce**
Just selecting specific images.

**Expected behavior**
The image should show in the preview.

**Source Image**

**Source Image or Screenshots**

**Additional context**

Log file shows this:

```
30/04/2023 19:38:17: An error occurred while reading xxxx.jpg: Could not load file or assembly 'XmpCore, Version=6.1.10.1, Culture=neutral, PublicKeyToken=961f4f366277b80e'. El sistema no puede encontrar el archivo especificado.

   at MetadataExtractor.Formats.Xmp.XmpReader.ReadJpegSegments(IEnumerable`1 segments)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.ProcessJpegSegments(IEnumerable`1 readers, ICollection`1 segments)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.Process(Stream stream, ICollection`1 readers)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.ReadMetadata(Stream stream, ICollection`1 readers)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.ReadMetadata(String filePath, ICollection`1 readers)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()

```
It can't find the XmpCore library, which is not part of the zip. Unless it is included inside the exe, but probably not since it fails.

**Comment by RupertAvery** [comment]
Thanks for catching this. 

You can try the Updater and see if it downloads v1.2.1 for you, otherwise you can grab the latest release here:

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/v1.2.1
