### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skunkworxdark** [RupertAvery/DiffusionToolkit#108]
I get the following error while scanning my invokeai outdir with 1.2.1

03/05/2023 19:07:15: ===========================================
03/05/2023 19:07:15: Started Diffusion Toolkit 1.2.1
03/05/2023 19:07:15: Opening database at C:\Users\neil_\AppData\Roaming\DiffusionToolkit\diffusion-toolkit.db
03/05/2023 19:07:15: Creating Thumbnail loader
03/05/2023 19:07:30: Initializing pages
03/05/2023 19:07:30: Loading models
03/05/2023 19:07:30: 0 models loaded
03/05/2023 19:07:30: Init completed
03/05/2023 19:07:36: An error occurred while reading C:\AI\invokeai\outputs\000001.ea8a8873.1210632489.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

   at System.Text.Json.JsonElement.EnumerateArray()
   at Diffusion.IO.Metadata.ReadInvokeAIParametersNew(String file, IEnumerable`1 directories)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()
03/05/2023 19:07:36: An error occurred while reading C:\AI\invokeai\outputs\000002.c0e1308b.1335881098.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

   at System.Text.Json.JsonElement.EnumerateArray()
   at Diffusion.IO.Metadata.ReadInvokeAIParametersNew(String file, IEnumerable`1 directories)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()
03/05/2023 19:07:36: An error occurred while reading C:\AI\invokeai\outputs\000003.8f7fa2f0.3028328294.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

   at System.Text.Json.JsonElement.EnumerateArray()
   at Diffusion.IO.Metadata.ReadInvokeAIParametersNew(String file, IEnumerable`1 directories)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()
03/05/2023 19:07:36: An error occurred while reading C:\AI\invokeai\outputs\000004.75033696.578057650.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

   at System.Text.Json.JsonElement.EnumerateArray()
   at Diffusion.IO.Metadata.ReadInvokeAIParametersNew(String file, IEnumerable`1 directories)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()

**Comment by RupertAvery** [comment]
Can you provide sample images that are affected?

**Comment by skunkworxdark** [comment]
Sure. But it is all images from my invokeai.  
![009041 a5cd2a4f 1889587062](https://user-images.githubusercontent.com/21961335/236143031-6764ad6c-6bb3-40b4-bd12-a73790d26eef.png)

**Comment by RupertAvery** [comment]
This is enough.

It looks like a slight format change in how the prompt is stored in the metadata, at least from a previous sample I recieved.

**Comment by skunkworxdark** [comment]
Did you need any more examples?

**Comment by skunkworxdark** [comment]
Thank you. That seems to have done the trick as it now imports all the images.  However it doesn't show the name of the model used. 

![image](https://user-images.githubusercontent.com/21961335/236187108-df00b56b-3426-481f-85f9-5ffa640ba71b.png)

**Comment by RupertAvery** [comment]
is it "Stable Diffusion"?

**Comment by skunkworxdark** [comment]
i've loaded that image into the PNGInfo part of Automatic1111 and it seems like the model name is in the data.  here is the data that PNGInfo shows.

parameters

None


Dream

"a discord of pastertarians marvelling at the spagtime rifts [<neg-sketch-2>]" -s 100 -S 1133696512 -W 960 -H 640 -C 5.5 -A k_dpmpp_2 --hires -f 0.75


sd-metadata

{"model": "stable diffusion", "model_weights": "edgeOfRealism_eorV20Fp16BakedVAE", "model_hash": "e7e9784ea4ffc1e9de02814e49f1bbd562e54a852ad0201853a67eceeb729b29", "app_id": "invoke-ai/InvokeAI", "app_version": "2.3.5", "image": {"prompt": "a discord of pastertarians marvelling at the spagtime rifts [<neg-sketch-2>]", "steps": 100, "cfg_scale": 5.5, "threshold": 0, "perlin": 0, "height": 640, "width": 960, "seed": 1133696512, "hires_fix": true, "seamless": false, "type": "txt2img", "postprocessing": null, "sampler": "k_dpmpp_2", "variations": []}}

**Comment by skunkworxdark** [comment]
Did you have any look investigating this at all?

**Comment by skunkworxdark** [comment]
is there anything I can do with helping to sort this out?

**Comment by skunkworxdark** [comment]
any further news?

**Comment by RupertAvery** [comment]
Sorry for the delay

Does this fix the issue?

[v1.3.zip](https://github.com/RupertAvery/DiffusionToolkit/files/12776545/v1.3.zip)

**Comment by skunkworxdark** [comment]
I wish I could test this for you but InvokeAI has moved forwards quite a bit now and has changed the Metadata format quite a bit now.  They are on version 3.2 now.   The final metadata format is still in flux a bit.  If your interested you should take a look at it as it has improved a fair bit now.  They have a SQLite db that keeps track of the images they store now so having some kind of integration into that would be great as the DB and the images on disk should match.
