### ISSUE TITLE
[BUG] Scan folder missing thousands

### ISSUE THREAD

**Issue by Ayelwen** [RupertAvery/DiffusionToolkit#118]
**Describe the bug**
When setting up Diffusion Toolkit and adding the Outdir which contains the generations, the toolkit only finds 24 out of several thousand. The InvokeAI outdir folder structure has some subfolders for Thumbnails which I put in Exclude as I don't want those and I don't want duplicates.

**Version:**
I was first using 1.2.1 and had the issue, but also tried the 1.2.2 posted in Issues on github and it didn't seem to have any effect.

**To Reproduce**
Generate using latest InvokeAI and nothing shows up.

**Expected behavior**
I expect to be able to view my generations

**Source Image**
![003261 bec06c52 2833162770](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/88e34747-66a6-4ca0-936f-eaaab3dfc3d9)

**Source Image or Screenshots**
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/bed38f73-142a-4cb7-af2f-c3fdba2f008f)
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/2ba73668-b981-4721-a2a3-cb47db171bca)

**Additional context**

**Comment by RupertAvery** [comment]
Can you show me your General settings?

Do you have Recursive checked?

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/1910659/1d8bcfae-33b8-4436-80bf-30e391929701)

The image you provided loads properly. Does it also load properly in your case? Is it part of the 24 images?

I will need a sample of images that do not load for you. Also, please attach your DiffusionToolkit.log file if it contains any error messages.

**Comment by Ayelwen** [comment]
General settings:
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/f1ba44e4-56d0-4c81-ac7a-33d0a8889a83)

I do have recursive checked (screenshot). The files are just PNG which is in the list.
The image I shared is not part of the 24 it discovers. 
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/ea5d2275-61ee-4f0d-a1e7-b80f73a0ee22)

**Comment by Ayelwen** [comment]
I went ahead and did another test as follows (incase the subfolder exclusions were related to the problem)
1. I noticed that Thumbnails are webm files while the generations are PNGs.
2. So I removed webm as a file extension in the tool, and removed all the exclusions.
3. rescanned but still only shows a few files. screenshot the folder as well showing the number and file type
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/8fd38711-001b-4066-af2e-69b44cfb3fb7)

**Comment by RupertAvery** [comment]
Hello, sorry for the delay. I've been busy with other things.

Can you upload somewhere a set of images, maybe 10-20, that you're sure don't work? I can't seem to replicate your issue with the image you provided.

Also, is there any error listed in diffusion-toolkit.log?

**Comment by Ayelwen** [comment]
Sorry, I never got back to you. I will get those now.

**Comment by Ayelwen** [comment]
okay, yes, there are thousdands of errors. its a really long file.
 An error occurred while reading C:\Users\ayelw\invokeai\outputs\000001.f75fd3bd.3539081754.postprocessed.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

   at System.Text.Json.JsonElement.EnumerateArray()
   at Diffusion.IO.Metadata.ReadInvokeAIParametersNew(String file, IEnumerable`1 directories)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.Scanner.Scan(IEnumerable`1 files)+MoveNext()
5/29/2023 4:08:39 PM: An error occurred while reading C:\Users\ayelw\invokeai\outputs\000005.66a11412.874975903.postprocessed.png: The requested operation requires an element of type 'Array', but the target element has type 'String'.

**Comment by Ayelwen** [comment]
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/e1bb7142-79ab-4679-8698-405b0354aba3)

**Comment by Ayelwen** [comment]
![image](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/d01da0c4-638e-46d5-960f-82434138e264)

**Comment by Ayelwen** [comment]
Anyone know if Avery went on vacation?

**Comment by RupertAvery** [comment]
I'm in the process of moving to another country, also been a bit busy with work, so apologies if I haven't been able to look into issues.  I promise I will do so, when I'm freed up.  The move will happen in the next two months, but hopefully I can find some time to squeeze in a few fixes.  Thanks for holding up!

**Comment by RupertAvery** [comment]
Hi, can you attach some of the images that have that specific error?

**Comment by Ayelwen** [comment]
yes sir! However, there is a slight change now.
All of the above is Invoke 2.3.# behavior. Invoke just completed a complete rewrite of their system about a week ago.
Invoke 3.0 images your Diffusion Toolkit is finding and adding to the library, but it is not detecting the metadata. I will attach the following images:
1. Direct image that was generated
2. Screenshot from your tool where it found the image, but no metadata
3. Screenshot from Invoke 3 showing the metadata

**Comment by Ayelwen** [comment]
![b48e8f64-e84d-4aa8-8991-2448e03d4756](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/2dd53d53-25e6-4644-9a88-d636c1944707)
![2023-08-02_13h55_08](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/3a2b663f-eaa8-4392-bd92-376d8e692535)
![2023-08-02_13h57_00](https://github.com/RupertAvery/DiffusionToolkit/assets/21064333/c4f644ac-b8be-4ee9-aa73-547c70e1efca)

**Comment by RupertAvery** [comment]
This looks like a new metadata format for InvokeAI.

I've added support for it.

**Comment by RupertAvery** [comment]
Let me know if the latest version 1.3 fixes this issue
