### ISSUE TITLE
[BUG] An unhandled exception occurred. Start index cannot be larger than length of string.

### ISSUE THREAD

**Issue by montyfi** [RupertAvery/DiffusionToolkit#147]
Cannot use toolkit at all. After the initial settings screen it shows error "Start index cannot be larger than length of string. (Parameter StartIndex)"

Version 1.4 windows, freshly downloaded.

I have added 4 folders, A111 output, standalone ComfyUI output, and an archive folders.

==============================================================================
09/11/2023 11.30.52: Initializing pages
09/11/2023 11.30.52: Loading models
09/11/2023 11.30.52: An unhandled exception occured: startIndex cannot be larger than length of string. (Parameter 'startIndex')

   at System.String.Substring(Int32 startIndex, Int32 length)
   at Diffusion.Toolkit.MainWindow.LoadModels()
   at Diffusion.Toolkit.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Diffusion.Toolkit.App.Main()

**Comment by Katmoget** [comment]
I have the same error on startup after update to 1.4 and fresh install
![Screenshot 2023-11-09 093020](https://github.com/RupertAvery/DiffusionToolkit/assets/113855232/41b7d812-7294-4101-813b-ab11fb2a5e6b)
when I click OK the program shut down

**Comment by f-rank** [comment]
Getting this too now.

**Comment by RupertAvery** [comment]
Did you set up the path to cache.json?

Can you post your cache.json?

**Comment by montyfi** [comment]
> Did you set up the path to cache.json?
yes
 
> Can you post your cache.json?
It's pretty huge, zipped it and attached.
[cache.zip](https://github.com/RupertAvery/DiffusionToolkit/files/13309213/cache.zip)

**Comment by RupertAvery** [comment]
I have some fixes, please try redownloading the same version

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/v1.4

**Comment by montyfi** [comment]
> I have some fixes, please try redownloading the same version

It is working now, thank you for the fix!
