### ISSUE TITLE
[BUG] 'N' is an invalid start of a value. LineNumber: 0

### ISSUE THREAD

**Issue by montyfi** [RupertAvery/DiffusionToolkit#148]
Version 1.4 windows, freshly downloaded.

Multiple errors such below during folder scan (image attached):

09/11/2023 11.25.52: An error occurred while reading C:\Soft\ComfyUI_windows_portable\ComfyUI\output\TEST_2023-11-05\PA_0213.png: 'N' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 954.

at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan1 bytes) at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) at System.Text.Json.Utf8JsonReader.ReadSingleSegment() at System.Text.Json.Utf8JsonReader.Read() at System.Text.Json.JsonDocument.Parse(ReadOnlySpan1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter) at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory1 json, JsonDocumentOptions options)
at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
at Diffusion.IO.Metadata.ReadComfyUIParameters(String file, String description)
at Diffusion.IO.Metadata.ReadFromFile(String file)
at Diffusion.IO.MetadataScanner.Scan(IEnumerable`1 files)+MoveNext()

![PA_0213](https://github.com/RupertAvery/DiffusionToolkit/assets/6643755/93ef7531-19d0-4018-a65f-15f6a48f1d4b)

**Comment by RupertAvery** [comment]
it looks like this is the culprit:

```
"is_changed": [NaN]
```
from

```
    "112": {
        "inputs": {
            "text": "alcohol marker flat colors, drawing, fullbody, solo, portrait of a Afro-Latinx woman, bowl cut hair, Body Shape Oval, Downturned Eyes, Doing a Thumbs-Up, shooting a gun into camera, james bond opening style, in retro futuristic Grove, Business Casual Attire, 60s style, concept art by syd mead, Morning, Windy Day\n, artistic, creative, contrasting, detailed, 8k, expressive"
        },
        "class_type": "DPRandomGenerator",
        "is_changed": [NaN]
    },
```

NaN is not a valid value, so the node is generating invalid json. I think.

I can throw in a quick fix that might work, but perhaps the main issue is the node itself?  This doesn't seem to be an issue with this version, could be happening on earlier versions.

**Comment by montyfi** [comment]
Thank you, I have just found your tool, I don't know how it was with previous versions, sorry. But according the log it says that about all my ComfyUI files. I'm using this dynamic prompts for comfy:
https://github.com/adieyal/comfyui-dynamicprompts

**Comment by RupertAvery** [comment]
Please try the latest build (same version number)

https://github.com/RupertAvery/DiffusionToolkit/releases/tag/v1.4

**Comment by montyfi** [comment]
No errors in the log anymore, thank you!
