### ISSUE TITLE
[BUG] Image not displayed, The given key was not present

### ISSUE THREAD

**Issue by Kluvwen** [RupertAvery/DiffusionToolkit#259]
Using primarily Novel AI, the error The given key was not present in the dictionary. has been occurring frequently as of some updates from them.
9/20/2024 12:26:56 AM: An error occurred while reading C:\Users\Kluvw\Downloads\AI\_{{{{{zero pictured}}}}}, castle s-3338614828.png: The given key was not present in the dictionary.

   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Diffusion.IO.Metadata.ReadFooocusMREParameters(String data)
   at Diffusion.IO.Metadata.ReadFromFile(String file)
   at Diffusion.IO.MetadataScanner.Scan(IEnumerable`1 files)+MoveNext()
**Version:**
Diffusion Toolkit 1.7 Fix

**Tool:**
NovelAI

**To Reproduce**
This isn't happenning with every image, however it is happening frequently, with no change in prompt or methodology.

**Expected behavior**
This is not expected, particularly images not showing at all, I was not aware this was an issue for some time until one I'd just added wasn't showing up and checking the log.

**Affected Image(s)**
![_{{{{{zero pictured}}}}}, castle s-3338614828](https://github.com/user-attachments/assets/d152b0e2-7958-4b22-829c-fd9f821477ec)

If possible, it would be preferable to show images even if they're producing an error if error allows for images to be shown.

**Comment by RupertAvery** [comment]
Thanks for finding this.

This build should resolve your issue while I am adding features and bug fixes for the next release.

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/10975406944/artifacts/1962103501

**Comment by Kluvwen** [comment]
Thanks so much, that looks to resolve both issues.

**Comment by RupertAvery** [comment]
Yes keep it open for now in case anyone else has the same issue, thanks!
