### ISSUE TITLE
[BUG] Unable to scan .png files

### ISSUE THREAD

**Issue by pontusic** [RupertAvery/DiffusionToolkit#263]
**Describe the bug**
Hi, I saved my images from SwarmUI or ComfyUI into png format but they do not appear in Diffusion Toolkit.
When I switch to jpg files, they turn up.

Both .png and .jpg are file extensions set for the Toolkit

**Version:**
1.6.1, 1.7, 1.7-FIXED

**Tool:**
ComfyUI, SwarmUI

**To Reproduce**
Generate PNG images on ComfyUI or SwarmUI

**Expected behavior**
The images appear in the folders but they do not turn up in scans of the folders by Diffusion Toolkit.

**Affected Image(s)**
PNG type images

**Comment by RupertAvery** [comment]
Hi, sorry for the late reply.

Are you still having problems with this? Can you post sample images?

**Comment by VV828** [comment]
I'm having the same issue with pictures generated by SwarmUI v0.9.5-Beta and DiffusionTookit v1.8. Here's an example image:

![Image](https://github.com/user-attachments/assets/fbf8a19a-221d-429f-a628-509fcf764805)

This is the error shown in DiffusionToolkit: 

```
The given key was not present in the dictionary.

   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Diffusion.IO.Metadata.ReadFooocusParameters(String data)
   at Diffusion.IO.Metadata.ReadRuinedFooocusParameters(String data)
   at Diffusion.IO.Metadata.ReadFromFileInternal(String file)
   at Diffusion.IO.Metadata.ReadFromFile(String file)```

**Comment by RupertAvery** [comment]
Thank you for the image. I have a fix in place that will be included in the next release, hopefully soon.

**Comment by VV828** [comment]
> Thank you for the image. I have a fix in place that will be included in the next release, hopefully soon.

Amazing, thanks!

**Comment by RupertAvery** [comment]
A new stable build is up, please try this:

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/14348000145/artifacts/2908080007
